### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by bruceamurphy** [uym2/TreeShrink#10] opened 2019-06-03 07:01 UTC
Hi,
I'm getting this error running treeshrink. My installation works on a different dataset but I can't see what's causing the error with this one. 
Traceback (most recent call last):
  File "/rds/general/user/bam114/home/software/TreeShrink/run_treeshrink.py", line 252, in <module>
    main()
  File "/rds/general/user/bam114/home/software/TreeShrink/run_treeshrink.py", line 99, in main
    r = a_filter.min_diams[i-1]/a_filter.min_diams[i]
ZeroDivisionError: float division by zero

It seems to process some of the files in the directory before falling over but I'm not certain which order it does this in so can't detect a problem with a particular alignment or treefile.

These are the options i'm using:
run_treeshrink.py -i treeshrink -a exon.fasta -t exon.tre -r $HOME/software/TreeShrink -c > treeshrink.log

I installed the code through conda and it seems to be version 2.2

**Comment by uym2** [comment] 2019-06-04 17:09
Hello,

The issue is caused when there are small trees in the dataset that have less than k leaves so that after removing, their diameter is 0. The issue was fixed in version 1.2.3 where there are warning messages but the code will still run. Can you please re-install from the conda to make sure you have the up-to-date version (1.3.1). Please let us know if you still see this problem or cannot install the new version.

**Closed** 2020-06-03 20:00 UTC
